### PR TITLE
Compatibility with Samsung and HTC based ROMs

### PR DESCRIPTION
**Pull request by helmasaur**
Samsung and HTC based ROMs uses a different font file name for emojis.

### CODE REVIEW

**Comment by simonsmh** [comment]
#6

**Comment by helmasaur** [comment]
What do you try to tell me with this link?

**Comment by simonsmh** [comment]
TL;DR, we don't need or even accept this kind of patch. This is a waste of resources.
I parse the fonts.xml to make sure that the correct emoji fonts name is selected that we could make a copy for every Android system, not only for Samsung or HTC but also for more other systems that we don't use before. This has already been fixed once for all.
Reference: https://github.com/Magisk-Modules-Repo/blobmoji/blob/master/install.sh#L138-L145

**Comment by helmasaur** [comment]
Oh, I see what you mean. This is a good idea!

**Pull request closed without merging**
