### PR TITLE
Added blob themed versions of the new unicode 10 emojis

### PR DESCRIPTION
**Pull request by thayerfox**
I've manually added a blob-ified version of the new oreo emojis from here:
https://www.reddit.com/r/Android/comments/71ktpe/i_turned_some_of_the_new_oreo_emojis_into_blobs/

Let me know if you are interested.  (I liked the older blob emojis where they had some different shapes better.  I have another version where I only added the new blobs and didn't change any of the old ones, if you like that better, but from what I have read online, people liked the different shapes more.)

### CODE REVIEW

**Comment by simonsmh** [comment]
Thanks! I really like that blob-ify design!
But where did you got the font file?

**Comment by thayerfox** [comment]
I extracted the old file using https://github.com/MitchTalmadge/Emoji-Tools/releases and then manually edited the font.ttx file to add new ones.  It took a little bit of time, but it worked.  Unfortunately, that tool is not compatible with the newer font files, and will only extract them to PNG, not recompile them.

**Comment by simonsmh** [comment]
Never mind! The font works very well, and you are doing amazing jobs!

**Comment by thayerfox** [comment]
Thanks for making the module to begin with.  I smile every time I see the blobs!

**Pull request merged**
